### ISSUE TITLE
fix next-speaker logic

### ISSUE THREAD

**Issue by jcomeauictx** [MyTurn-OpenSource/pyturn#9]
I noticed when testing that a speaker is allowed to finish speaking to a multiple of the "turn" time even though another in the speaker pool has precedence. the logic needs to be overhauled.

**Comment by DavidStodolsky** [comment]
The basic rules are quantum allocation and equal-time resolution. Once a turn has been allocated, it can be used to completion. So, having used less time is only relevant at resolution time - at the transition from speaker to speaker. The experimental results support the benefits of this configuration, so we will maintain it until we have evidence that an alternative is better.

**Comment by DavidStodolsky** [comment]
Allowing interruption of a speaker opens the possibility of gaming the system and may be less effective even without strategic considerations. Equal-time resolution already motivates the speaker to conclude as quickly as possible in order to have easy access later in the conversation. A purely time-based allocation system assumes equal competence of all users. Since this assumption can hardly be justified, improvements are likely to come from a structure that compensates for competence differences. In the first instance, this can be done via a priority system that doesn't require interruptions.
[Self-management of Criticism in Dialogue.pdf](https://github.com/MyTurn-OpenSource/pyturn/files/1401743/Self-management.of.Criticism.in.Dialogue.pdf)

Long version: 
[Self-management of Criticism in Dialogue (long).pdf](https://github.com/MyTurn-OpenSource/pyturn/files/1401756/Self-management.of.Criticism.in.Dialogue.long.pdf)

**Comment by DavidStodolsky** [comment]
The need for interruptions can be tuned with the current system by adjusting the "turn time." By making it just a few seconds, interrupts are effectively permitted. This, however, undermines the ability of a speaker to make a longer point. A fully built-out system for meeting management would allow certain types of interruptions. In Roberts Rules of Procedure, 17 levels of priority are specified. The highest allow interruption. For example, a "Point of Order." http://diphi.web.unc.edu/files/2012/02/MSG-ROBERTS_RULES_CHEAT_SHEET.pdf

**Comment by jcomeauictx** [comment]
OK, I was thinking I had the logic wrong, and that it was *supposed* to switch mid-turn if the speaker had already used a full quantum. since it's correct I'll close this.
